import $ from 'jquery'
import Inputmask from "inputmask";
import 'bootstrap/js/src/util'
import 'bootstrap/js/src/modal'
import 'bootstrap/js/src/tab'
import '../../node_modules/jquery-selectric/src/jquery.selectric.js'
import '../../node_modules/slick-carousel/slick/slick.js'
// import '../../node_modules/inputmask/dist/jquery.inputmask.js'
import './components/jVForms/jVForms.js'

import './components/common'
import './components/hero-slider'
import './components/services-slider'
import './components/product-slider'
import './components/product-review'
import './components/product-about'
import './components/models_slider'
import './components/checkbox'
import './components/search'
import './components/faq'
import './components/features'
import './components/new-car'
import './components/content-gallery-slider'
import './components/blog-slider'
import './components/auto-item'
import './components/catalog'
import './components/form'
//123